[package]
name = "day2"
version = "0.1.0"
authors = ["Rene Leveille <rene.leveille@polymtl.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.36"
argh = "0.1.4"
itertools = "0.9.0"
peg = "0.6.3"
